readme added
jiwonkim19/joytech-app pull request #1
Opened 2022-04-07 03:40 UTC by jiwonkim19

Added instructions to readme.md file. Try to install and let me know if you have any problems.

2022-04-07 04:16 UTC, eternal44 commented on README.md
> +  $ python3 -m pip install < backend-dependency>
I found this command that will install everything in the `requirements.txt` file with one command:
```
python3 -m pip install -r requirements.txt
```

2022-04-07 04:16 UTC, eternal44 commented on README.md
> +  $ npm install <frontend-dependency>
Same - you can run `npm install` and it'll install everything in your `package.json` file.

2022-04-07 04:16 UTC, eternal44 commented on README.md
> +* Create a database in Postgres
What should the database be called?

Also, adding the command to create the db would be nice. Something like:
```
createdb joytech_development
```

or something.

2022-04-07 04:17 UTC, eternal44 commented on README.md
> +* Install Python 3.9.10:
I couldn't install 3.9.10 so I'm going to try with 3.8.10... hopefully it just works :P

2022-04-07 04:37 UTC, jiwonkim19 commented on README.md
> +  $ python3 -m pip install < backend-dependency>
ok. updated

2022-04-07 04:38 UTC, jiwonkim19 commented on README.md
> +  $ npm install <frontend-dependency>
updated

2022-04-07 04:41 UTC, jiwonkim19 commented on README.md
> +* Create a database in Postgres
Hey! So I gave the dev the freedom to name their own database. As long as it correlates with the .env file, they should be fine.

2022-04-08 17:19 UTC, eternal44 commented on README.md
> +* Create a database in Postgres
Sounds good!

2022-04-08 17:22 UTC, eternal44 requested changes
I was able to spin up the frontend and backend servers as well as create a request - looks like I'm good to start!

I'll keep an eye out on my different python version. If it becomes a problem down the line we can tackle it then.

Lastly, can you add the command to create a database? Everything else LGTM!

2022-04-09 21:21 UTC, jiwonkim19 commented on README.md
> +* Install Python 3.9.10:
Yep. Let me know if you run into any trouble.

2022-04-09 21:29 UTC, closed without merging